name: secure_app_switcher
description: Apply a safe masking effect to the app screen on the app switcher or task list.
version: 1.0.0
repository: https://github.com/arkwycr/secure_app_switcher
issue_tracker: https://github.com/arkwycr/secure_app_switcher/issues

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arkwycr.secure_app_switcher
        pluginClass: SecureAppSwitcherPlugin
      ios:
        pluginClass: SecureAppSwitcherPlugin